apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: shop-db-spc
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "shop-db-secret-1"
        objectType: "secretsmanager"
